[package]
name = "examples"
edition = "2021"
version = "0.0.1"

[dev-dependencies]
vexide = { path = "packages/vexide" }

[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.lints.rust]
rust_2018_idioms = "warn"
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
missing_const_for_fn = "warn"
