[package]
name = "vexide-panic"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Panic handler for vexide"
keywords = ["Robotics", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vexide-core = { version = "0.3.0", path = "../vexide-core" }
vexide-devices = { version = "0.3.0", path = "../vexide-devices", optional = true }
vex-sdk = "0.18.0"

[features]
default = ["display_panics"]

display_panics = ["dep:vexide-devices"]

[lints]
workspace = true
